<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE perifericos [
   <!ELEMENT perifericos (#PCDATA)>
]>

<perifericos>
   impresora
    monitor
   teclado
</perifericos>

<!DOCTYPE perro [
   <!ELEMENT perro (edad, nombre)>
   <!ELEMENT edad (#PCDATA)>
   <!ELEMENT nombre (#PCDATA)>
]>


<perro>
  <edad>8></edad>
  <nombre>Panchedadbre</nombre>
</perro>

<!DOCTYPE caballo [
   <!ELEMENT caballo (nombre, raza, edad)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT raza (#PCDATA)>
   <!ELEMENT edad EMPTY>
]>

<caballo>
   <nombre>Silvestre</nombre>
   <raza>Morgan</raza>
   <edad />
</caballo>

<!DOCTYPE mesa [
   <!ELEMENT mesa ANY>
   <!ELEMENT material (#PCDATA)>
   <!ELEMENT color (#PCDATA)>
]>

<mesa>La mesa de <material>madera</material> es de color <color>marr√≥n</color>.</mesa>